#cloud-config

---
coreos:
  units:
    - name: '00-enp2s0f0.network'
      runtime: true
      content: |
        [Match]
        Name=enp2s0f0

        [Network]
        Gateway=10.0.0.1
        DNS=10.0.0.1
        Address=10.0.0.115/24
ssh_authorized_keys:
  - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDAw5aSSRjf8m3ZTH+VxXdr8ZiCod0n5XOH0gP/xPREY1zKST3PTUpEiEizf5NcNNT0twJ8qK+zmrsBEVTB0maMswSXQnufAP32quNmJwRTqFFeW7GpTEOt3ZqJIHM4qBzptviDRCbt54TAcSGu28dc57Y+n6zz1vey03XpI/5Gf4QaEO9ijPDut6qq1FMWMBzcuGlZkodOnpPl32RCcU6YipnTixV6m8W4HDiLZimdnMnKIRmVbTwfoR4/DJDX/bj2Z89XBrz8RV942Yd1MarTgzwEiW61nxVLNNzINiU6Vvkh6CKKa694PyCQCLHlYH4jWYAMsc7KRI3rJ4lwy1in'
  - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDFTGI9xobfEmMLPCXYDbfGbWP8Y83wmEl3MB8e4pffZKCYwBKPwTNwNQvnuOI3ZQm1d7X5vwGMcQf/sSqaLVrOZQTQeQP01jFPPT7eaTFQP+vgTE6CMjdxWNHOZqlpS92Clg4MLJBi3PKjyTsXw1M05h+uAm7Mlsws7wCeQrjvYNDpY5u3ysSdjRPxr1bkmcXgQb27Eb8zjJwfppZvulzvfjDgGhiouxmej3q5eByq3eTrKgFiw5eyjnvO4EjzzFlc/M3KTxbpBKgoS+cnEt/11mGzGsQ9GpAWZWwH+ut0NnFRxjhfPhH7Xr3sa5honcb9QJ9pnEZFoUmFKFUNAKzR'
