#cloud-config

---
coreos:
  units:
    - name: '00-enp2s0f0.network'
      runtime: true
      content: |
        [Match]
        Name=enp2s0f0

        [Network]
        Address='10.0.0.115/24'
ssh_authorized_keys:
  - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDAw5aSSRjf8m3ZTH+VxXdr8ZiCod0n5XOH0gP/xPREY1zKST3PTUpEiEizf5NcNNT0twJ8qK+zmrsBEVTB0maMswSXQnufAP32quNmJwRTqFFeW7GpTEOt3ZqJIHM4qBzptviDRCbt54TAcSGu28dc57Y+n6zz1vey03XpI/5Gf4QaEO9ijPDut6qq1FMWMBzcuGlZkodOnpPl32RCcU6YipnTixV6m8W4HDiLZimdnMnKIRmVbTwfoR4/DJDX/bj2Z89XBrz8RV942Yd1MarTgzwEiW61nxVLNNzINiU6Vvkh6CKKa694PyCQCLHlYH4jWYAMsc7KRI3rJ4lwy1in'
